# plugins/multi-dkim.toml
["modules/@mindbaz/zonemta-multi-dkim"]
enabled="sender"

# Header who contain key name
key_header = "random-header"

# Keys list, used to valid keys file name without extention .pem
keys = [
  "random-domain-1",
  "random-domain-2",
  "random-domain-3"
]

# Keys directory
keys_dir = "/path/to/zone-mta/keys"

# Selector value for all
selector = "test"

# If true then uses the same key to add a signature for the hostname of the outbound IP address
signTransportDomain = true
